---
- name: show module info
  hosts: all
  gather_facts: false

  tasks:
        - name: Show Huawei slots
          ce_command:
                  commands:
                      - 'display device pic-status'
          register: vrp
          when: ansible_network_os == 'ce'
        
        
        - name:  Show Cisco IOS XR slots
          cisco.iosxr.iosxr_command:
                  commands:
                      - admin show platform 
          register: iosxr
          when: ansible_network_os == 'cisco.iosxr.iosxr'
        
        - name: Show Cisco IOS slots
          cli_command:
                  command: show module all
          register: ios
          when: ansible_network_os == 'ios'
        
        
        
        
        
        - name: Save to file
          copy:
                  content: " {{ vrp.stdout[0]}}"
                  dest: "/etc/ansible/routers/slots/{{inventory_hostname}}.txt"
          when: ansible_network_os == 'ce'    
        
        
        - name: Save to file IOS XR
          copy:
                  content: "{{ iosxr.stdout[0]}}"
                  dest: "/etc/ansible/routers/slots/{{inventory_hostname}}.txt"
          when: ansible_network_os == 'cisco.iosxr.iosxr'              
          
        
        - name: Save to file Cisco IOS
          copy:
                  content: "{{ ios.stdout[0]}}"
                  dest: "/etc/ansible/routers/slots/{{inventory_hostname}}.txt"
          when: ansible_network_os == 'ios'
        
        
        